In [1]:
## Import Libriaries
from sklearn.neural_network import MLPRegressor
import numpy as np

In [15]:
## Basic Data Array
## https://blog.finxter.com/tutorial-how-to-create-your-first-neural-network-in-1-line-of-python-code/
## Questionaire data (WEEK, YEARS, BOOKS, PROJECTS, EARN, RATING)
Q = [[20,  11,  20,  30,  4000,  3000],
     [12,   4,   0,   0, 1000,  1500],
     [2,   0,   1,  10,   0,  1400],
     [35,   5,  10,  70,  6000,  3800],
     [30,   1,   4,  65,   0,  3900],
     [35,   1,   0,   0,   0, 100],
     [15,   1,   2,  25,   0,  3700],
     [40,   3,  -1,  60,  1000,  2000],
     [40,   1,   2,  95,   0,  1000],
     [10,   0,   0,   0,   0,  1400],
     [30,   1,   0,  50,   0,  1700],
     [1,   0,   0,  45,   0,  1762],
     [10,  32,  10,   5,   0,  2400],
     [5,  35,   4,   0, 13000,  3900],
     [8,   9,  40,  30,  1000,  2625],
     [1,   0,   1,   0,   0,  1900],
     [1,  30,  10,   0,  1000,  1900],
     [7,  16,   5,   0,   0,  3000]]
X = np.array(Q)

In [3]:
## One-line Neural Network
neural_net = MLPRegressor(max_iter=2000).fit(X[:,:-1], X[:,-1])

C:\Users\jwill\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [4]:
## Result from all 0 inputs
res = neural_net.predict([[0, 0, 0, 0, 0]])
print(res)

[96.64461673]


In [5]:
## Result from revised input
res = neural_net.predict([[20, 0, 0, 0, 0]])
print(res)

[458.69307597]


In [6]:
## Result from another input
res = neural_net.predict([[20, 1, 10, 50, 1000]])
print(res)

[1941.55180546]


In [7]:
## New one with phlebotomy data
import os
os.getcwd()

'C:\\Users\\jwill\\Jupyter Notebooks'

In [8]:
%cd "C:\Users\jwill\Documents\Machine Learning\Data"

C:\Users\jwill\Documents\Machine Learning\Data


In [9]:
import pandas as pd
Y = pd.read_csv('phlebotomy.csv')

In [10]:
Y

SUV  Age    TS
0     5   48   7.8
1    15   56  10.9
2    20   61  20.9
3    25   41  22.5
4    30   34  22.3
5    30   48  34.4
6    30   41  19.2
7    35   41  37.4
8    40   48  46.6
9    40   30  47.0
10   50   23  63.3
11   50   25  63.6
12   55   21  56.6
13   65   21  79.6
14   65   30  57.3
15   65   19  82.7
16   70   28  71.4
17   70   31  58.4
18   70   36  70.0
19   70   28  67.1
20   90   27  97.5

In [16]:
Q

[[20, 11, 20, 30, 4000, 3000],
 [12, 4, 0, 0, 1000, 1500],
 [2, 0, 1, 10, 0, 1400],
 [35, 5, 10, 70, 6000, 3800],
 [30, 1, 4, 65, 0, 3900],
 [35, 1, 0, 0, 0, 100],
 [15, 1, 2, 25, 0, 3700],
 [40, 3, -1, 60, 1000, 2000],
 [40, 1, 2, 95, 0, 1000],
 [10, 0, 0, 0, 0, 1400],
 [30, 1, 0, 50, 0, 1700],
 [1, 0, 0, 45, 0, 1762],
 [10, 32, 10, 5, 0, 2400],
 [5, 35, 4, 0, 13000, 3900],
 [8, 9, 40, 30, 1000, 2625],
 [1, 0, 1, 0, 0, 1900],
 [1, 30, 10, 0, 1000, 1900],
 [7, 16, 5, 0, 0, 3000]]

In [27]:
## convert csv file to array
import numpy as np
data = np.genfromtxt('phlebotomy.csv', delimiter = ',', skip_header=1)
print (data)

[[ 5.  48.   7.8]
 [15.  56.  10.9]
 [20.  61.  20.9]
 [25.  41.  22.5]
 [30.  34.  22.3]
 [30.  48.  34.4]
 [30.  41.  19.2]
 [35.  41.  37.4]
 [40.  48.  46.6]
 [40.  30.  47. ]
 [50.  23.  63.3]
 [50.  25.  63.6]
 [55.  21.  56.6]
 [65.  21.  79.6]
 [65.  30.  57.3]
 [65.  19.  82.7]
 [70.  28.  71.4]
 [70.  31.  58.4]
 [70.  36.  70. ]
 [70.  28.  67.1]
 [90.  27.  97.5]]


In [28]:
## One-line Neural Network
neural_net = MLPRegressor(max_iter=2000).fit(data[:,:-1], data[:,-1])

C:\Users\jwill\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [29]:
## Result from inputs
res = neural_net.predict([[90, 27]])
print(res)

[101.60239479]


In [30]:
## Result from inputs
res = neural_net.predict([[50, 24]])
print(res)

[53.2906531]


In [31]:
data = np.genfromtxt('phlebotomy2.csv', delimiter = ',', skip_header=1)
print (data)

[[48.   7.8  5. ]
 [56.  10.9 15. ]
 [61.  20.9 20. ]
 [41.  22.5 25. ]
 [34.  22.3 30. ]
 [48.  34.4 30. ]
 [41.  19.2 30. ]
 [41.  37.4 35. ]
 [48.  46.6 40. ]
 [30.  47.  40. ]
 [23.  63.3 50. ]
 [25.  63.6 50. ]
 [21.  56.6 55. ]
 [21.  79.6 65. ]
 [30.  57.3 65. ]
 [19.  82.7 65. ]
 [28.  71.4 70. ]
 [31.  58.4 70. ]
 [36.  70.  70. ]
 [28.  67.1 70. ]
 [27.  97.5 90. ]]


In [32]:
## One-line Neural Network
neural_net = MLPRegressor(max_iter=2000).fit(data[:,:-1], data[:,-1])

C:\Users\jwill\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [36]:
## Resulting (task completion) from inputs (age, tech score)
res = neural_net.predict([[27, 9]])
print(res)

[15.30887358]
